name: QPG CI/CD

on:
  push:
    branches: [develop, qa, staging]
  workflow_dispatch:
  workflow_call:
    inputs:
      gameName:
        required: true
        type: string
      useTPBundling:
        required: false
        type: boolean
      deployTo:
        required: false
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true
      SLACK_WEBHOOK:
        required: true
      NODE_AUTH_TOKEN:
        required: true

jobs:
  checkout:
    runs-on: ubuntu-latest
    env:
      WORKING_PATH: /home/runner/work
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.gameName }}
          path: ${{ github.workspace }}/
  buildAtlas:
    runs-on: ubuntu-latest
    needs: [checkout]
    env:
      WORKING_PATH: /home/runner/work
    steps:
    - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/download-artifact@v3
        if: ${{ inputs.useTPBundling != '' }}
        with:
          name: ${{ inputs.gameName }}
          path: ${{ github.workspace }}/

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        if: ${{ inputs.useTPBundling != '' }}
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set QPG Key
        if: ${{ inputs.deployTo == '' }}
        run: |
          case "${GITHUB_REF##*/}" in
            "develop")
              qpgKey="DEV_QPG_CONFIG"
              qpgPrefix="DEV_"
            ;;
            "qa1")
              qpgKey="QA1_QPG_CONFIG"
              qpgPrefix="QA1_"
            ;;
            "qa")
              qpgKey="QA2_QPG_CONFIG"
              qpgPrefix="QA2_"
            ;;
            "staging")
              qpgKey="STAGING_QPG_CONFIG"
              qpgPrefix="STAGING_"
            ;;
          esac
          echo "QPG_KEY=$(echo $qpgKey)" >> $GITHUB_ENV
          echo "QPG_PREFIX=$(echo $qpgPrefix)" >> $GITHUB_ENV

      - name: Set QPG Key Manual Deploy
        if: ${{ inputs.deployTo != '' }}
        run: |
          case ${{ inputs.deployTo }} in
            "QA1")
              qpgKey="QA1_QPG_CONFIG"
              qpgPrefix="QA1_"
            ;;
            "develop")
              qpgKey="DEV_QPG_CONFIG"
              qpgPrefix="DEV_"
            ;;
          esac
          echo "QPG_KEY=$(echo $qpgKey)" >> $GITHUB_ENV
          echo "QPG_PREFIX=$(echo $qpgPrefix)" >> $GITHUB_ENV

      - name: Read secrets from AWS Secrets Manager into environment variables
        uses: abhilash1in/aws-secrets-manager-action@v2.1.0
        if: ${{ inputs.useTPBundling != '' }}
        with:
          secrets: ${{ env.QPG_KEY }}
          parse-json: true

      - name: Convert variables
        run: |
          readarray -t vars < <(compgen -A variable)
          declare -p vars
          echo $vars
          for item in "${vars[@]}"
          do
              if  [[ $item == $QPG_PREFIX* ]];
              then
                var=${item/$QPG_PREFIX/}
                echo "${var}=$(echo "${!item}")" >> $GITHUB_ENV
                  echo "key: " . $item
              fi
          done

      - name: Install TP and dependencies
        if: ${{ inputs.useTPBundling != '' }}
        run: |
          sudo apt-get update
          curl --output /tmp/tp.deb https://www.codeandweb.com/download/texturepacker/7.0.3/TexturePacker-7.0.3.deb
          sudo apt-get -y install libegl1-mesa libgl1-mesa-glx libfontconfig libx11-6 libxkbcommon-x11-0 /tmp/tp.deb
          echo agree | TexturePacker --version
          TexturePacker --activate-license ${QPG_CONFIG_QPG_TEXTURE_PACKER_KEY} ${{ github.workspace }}/raw_assets/*.tps

      - uses: actions/upload-artifact@v3
        if: ${{ inputs.useTPBundling != '' }}
        with:
          name: ${{ inputs.gameName }}
          path: ${{ github.workspace }}
  buildProject:
    runs-on: ubuntu-latest
    needs: [checkout, buildAtlas]
    steps:
    - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/download-artifact@v3
        id: download
        with:
          name: ${{ inputs.gameName }}
          path: ${{ env.WORKING_PATH }}

      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}

      - name: Install dependencies
        working-directory: ${{ steps.download.outputs.download-path }}
        run: npm ci

      - name: Build
        run: npm run build:dev

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set QPG Key
        if: ${{ inputs.deployTo == '' }}
        run: |
          case "${GITHUB_REF##*/}" in
            "develop")
              qpgKey="DEV_QPG_CONFIG"
              qpgPrefix="DEV_"
            ;;
            "qa1")
              qpgKey="QA1_QPG_CONFIG"
              qpgPrefix="QA1_"
            ;;
            "qa")
              qpgKey="QA2_QPG_CONFIG"
              qpgPrefix="QA2_"
            ;;
            "staging")
              qpgKey="STAGING_QPG_CONFIG"
              qpgPrefix="STAGING_"
            ;;
          esac
          echo "QPG_KEY=$(echo $qpgKey)" >> $GITHUB_ENV
          echo "QPG_PREFIX=$(echo $qpgPrefix)" >> $GITHUB_ENV

      - name: Set QPG Key Manual Deploy
        if: ${{ inputs.deployTo != '' }}
        run: |
          case ${{ inputs.deployTo }} in
            "QA1")
              qpgKey="QA1_QPG_CONFIG"
              qpgPrefix="QA1_"
            ;;
            "develop")
              qpgKey="DEV_QPG_CONFIG"
              qpgPrefix="DEV_"
            ;;
          esac
          echo "QPG_KEY=$(echo $qpgKey)" >> $GITHUB_ENV
          echo "QPG_PREFIX=$(echo $qpgPrefix)" >> $GITHUB_ENV

      - name: Read secrets from AWS Secrets Manager into environment variables
        uses: abhilash1in/aws-secrets-manager-action@v2.1.0
        with:
          secrets: ${{ env.QPG_KEY }}
          parse-json: true

      - name: Convert variables
        run: |
          readarray -t vars < <(compgen -A variable)
          declare -p vars
          echo $vars
          for item in "${vars[@]}"
          do
              if  [[ $item == $QPG_PREFIX* ]];
              then
                var=${item/$QPG_PREFIX/}
                echo "${var}=$(echo "${!item}")" >> $GITHUB_ENV
                  echo "key: " . $item
              fi
          done

      - name: Deploy Game
        run: aws s3 cp dist s3://${QPG_CONFIG_QPG_GHG_QPG_URL}/${{ inputs.gameName }} --recursive

      - name: Sync game
        run: aws s3 sync dist s3://${QPG_CONFIG_QPG_GHG_QPG_URL}/${{ inputs.gameName }} --delete --exact-timestamps

      - name: Invalidate dashboard cloudfront
        run: aws cloudfront create-invalidation --distribution-id ${QPG_CONFIG_QPG_AWS_CF_DIST_ID} --paths "/${{ inputs.gameName }}/*"

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: ${{ inputs.slackChannel || 'github-games-deploy' }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://www.goldenheartsgames.com/favicon.ico
          SLACK_TITLE: CI - ${{ inputs.gameName }}
          SLACK_USERNAME: ghg-deploy
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  cleanup:
    runs-on: ubuntu-latest
    needs: [buildProject]
    steps:
      - uses: geekyeggo/delete-artifact@v1
        with:
          name: ${{ inputs.gameName }}
