name: QPG CI/CD

on:
  push:
    branches: [ develop ]
  workflow_dispatch:
  workflow_call:
    inputs:
      gameName:
        required: true
        type: string
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true
      AWS_CF_DIST_ID:
        required: true
      GHG_DEV_URL:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v3

      - name: Version
        run: node -v

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.AWS_REGION }}

      - name: Deploy dashboard to bucket
        run: aws s3 sync dist s3://${{ inputs.GHG_DEV_URL }}/${{ inputs.gameName }} --delete

      - name: Invalidate dashboard cloudfront
        run: aws cloudfront create-invalidation --distribution-id ${{ inputs.AWS_CF_DIST_ID }} --paths "/${{ inputs.gameName }}/*"