name: Cypress Automation Tests

on:
  workflow_call:
    inputs:
      GAME_ID:
        required: true
        type: string
      GAME_NAME:
        required: true
        type: string
    secrets:
      PERSONAL_ACCESS_TOKEN:
        required: true
      NODE_AUTH_TOKEN:
        required: true

jobs:
  cypress-run-automation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: goldenheartsgames/game-framework
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ref: main

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}

      - name: Setup Framework dist so Cypress can build
        run: |
          npm ci
          npm run framework:bootstrap
          pushd packages/core
          npm i
          popd
          pushd packages/slots
          npm i
          popd
          pushd packages/scratch
          npm i
          popd
          pushd packages/bingo
          npm i
          popd

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          spec: |
            cypress/e2e/slots/automation-tests/*.cy.ts
          env: game_id=${{inputs.GAME_ID}}
          build: npm run framework:build

      - name: Get date
        run: |
          $NOW=& Get-Date -format yyyy-MM-dd
          echo "NOW=$NOW" >> $env:GITHUB_ENV

      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        with:
          name: AutomationTest-${{inputs.GAME_NAME}}-${{env.NOW}}
          path: cypress/screenshots/
