name: WebApp CI/CD

on:
  push:
    branches: [ develop, qa1, qa2, staging ]
  workflow_dispatch:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true
      SLACK_WEBHOOK:
        required: true
      NODE_AUTH_TOKEN:
        required: true

jobs:
  checkoutAndBuild:
    runs-on: ubuntu-latest
    env:
      WORKING_PATH: /home/runner/work
    steps:
      - uses: actions/checkout@v3
      - run: echo $GITHUB_WORKSPACE
      - run: ls $GITHUB_WORKSPACE
#      - uses: actions/setup-node@v3
#        with:
#          node-version: 16
#      - run: npm ci
#      - uses: actions/upload-artifact@v3
#        with:
#          name: webapp
#          path: webapp/
#  build:
#    runs-on: ubuntu-latest
#    needs: [ checkout ]
#    steps:
#      - name: AOT Build
#        run: |
#          APP_CONFIG_PATH="./src/app/app-config.module.ts"
#          echo "HelloWorld " . $APP_CONFIG_PATH
#  cleanup:
#    runs-on: ubuntu-latest
#    needs: [build]
#    steps:
#      - uses: geekyeggo/delete-artifact@v1
#        with:
#          name: webapp